<!DOCTYPE html>
<html lang="en-US">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="author" content="Jimmy Zhang" />
    <meta name="description" content="Describe your website">
    <link rel="shortcut icon" type="image/x-icon" href="../img/favicon.ico">
    <title>Project 2: Modeling, Testing, and Predicting</title>
    <meta name="generator" content="Hugo 0.70.0" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="../css/main.css" />
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:200,400,200bold,400old" />
    
    <!--[if lt IE 9]>
			<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
			<script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
		<![endif]-->

    
  </head>

  <body>
    <div id="wrap">

      
      <nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand" href="../"><i class="fa fa-home"></i></a>
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div class="navbar-collapse collapse" id="navbar">
      <ul class="nav navbar-nav navbar-right">
      
        
        <li><a href="../blog/">BLOG</a></li>
        
        <li><a href="../projects/">PROJECTS</a></li>
        
        <li><a href="resume.pdf">RESUME</a></li>
        
      
      </ul>
    </div>
  </div>
</nav>

      
      <div class="container">
        <div class="blog-post">
          <h3>
            <strong><a href="../project2/">Project 2: Modeling, Testing, and Predicting</a></strong>
          </h3>
        </div>
        <div class="blog-title">
          <h4>
          January 1, 0001
            &nbsp;&nbsp;
            
          </h4>
        </div>
        <div class="panel panel-default">
          <div class="panel-body">
            <div class="blogpost">
              


<div id="modeling" class="section level1">
<h1>Modeling</h1>
<div id="instructions" class="section level2">
<h2>Instructions</h2>
<p>A knitted R Markdown document (as a PDF) and the raw R Markdown file (as .Rmd) should both be submitted to Canvas by 11:59pm on 5/1/2020. These two documents will be graded jointly, so they must be consistent (i.e., don’t change the R Markdown file without also updating the knitted document). Knit an html copy too, for later! In the .Rmd file for Project 2, you can copy the first code-chunk into your project .Rmd file to get better formatting. Notice that you can adjust the opts_chunk$set(…) above to set certain parameters if necessary to make the knitting cleaner (you can globally set the size of all plots, etc). You can copy the set-up chunk in Project2.Rmd: I have gone ahead and set a few for you (such as disabling warnings and package-loading messges when knitting)!</p>
<p>Like before, I envision your written text forming something of a narrative structure around your code/output. All results presented must have corresponding code. Any answers/results/plots etc. given without the corresponding R code that generated the result will not be graded. Furthermore, all code contained in your final project document should work properly. Please do not include any extraneous code or code which produces error messages. (Code which produces warnings is acceptable, as long as you understand what the warnings mean).</p>
</div>
<div id="find-data" class="section level2">
<h2>Find data:</h2>
<p>Find one dataset with at least 5 variables that wish to use to build models. At least one should be categorical (with 2-5 groups) and at least two should be numeric. Ideally, one of your variables will be binary (if not, you will need to create one by discretizing a numeric, which is workable but less than ideal). You will need a minimum of 40 observations (<em>at least</em> 10 observations for every explanatory variable you have, ideally 20+ observations/variable).</p>
<p>It is perfectly fine to use either dataset (or the merged dataset, or a subset of your variables) from Project 1. However, you could also diversify your portfolio a bit by choosing a different dataset to work with (particularly if the variables did not reveal interesting associations in Project 1). The only requirement/restriction is that you may not use data from any examples we have done in class or lab. It would be a good idea to pick more cohesive data this time around (i.e., variables that you actually thing might have a relationship you would want to test). Think more along the lines of your Biostats project.</p>
<p>Again, you can use data from anywhere you want (see bottom for resources)! If you want a quick way to see whether a built-in (R) dataset has binary and/or character (i.e., categorical) variables, check out this list: <a href="https://vincentarelbundock.github.io/Rdatasets/datasets.html" class="uri">https://vincentarelbundock.github.io/Rdatasets/datasets.html</a>.</p>
</div>
<div id="guidelines-and-rubric" class="section level2">
<h2>Guidelines and Rubric</h2>
<ul>
<li><strong>0. (5 pts)</strong> Introduce your dataset and each of your variables (or just your main variables if you have lots) in a paragraph. What are they measuring? How many observations?</li>
</ul>
<pre class="r"><code>library(dplyr)
liftdatraw1 &lt;- readr::read_csv(&quot;https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-10-08/ipf_lifts.csv&quot;)
liftdataraw2&lt;-na.omit(liftdatraw1)
liftdata&lt;-liftdataraw2%&gt;%select(sex,event,equipment,age,division,&quot;bodyweight&quot;=bodyweight_kg,&quot;best3squat&quot;=best3squat_kg,&quot;best3bench&quot;=best3bench_kg,&quot;best3deadlift&quot;=best3deadlift_kg,place)
liftdata3&lt;-liftdataraw2%&gt;%select(sex, &quot;bodyweight&quot;=bodyweight_kg, &quot;maxsquat&quot;=best3squat_kg, &quot;maxbench&quot;=best3bench_kg, &quot;maxdead&quot;=best3deadlift_kg, equipment)
liftdata &lt;- liftdata[!is.na(as.numeric(as.character(liftdata$place))),]</code></pre>
<p>My dataset was found from GitHub’s Tidy Tuesday website and it contained information about powerlifting. Data about powerlifting competitions over time are included in the dataset. I will be focusing on seven of the variables described: bodyweight, sex, equipment type, place, max weight on three reps of deadlift, max weight on three repos of bench press, and max weight on thee reps of squats. The bodyweight variable is the weight of the individual powerlifter in kilograms. The max weight on three reps of deadlift, max weight on three repos of bench press, and max weight on thee reps of squats variables are all measured in kilograms. With that said, bodyweight, max weight on three reps of deadlift, max weight on three repos of bench press, and max weight on thee reps of squats are all numeric variables. The place is the result in standing of the competition in which the powerlifter participated in (ex. First place). The equipment type is a categorical variable in which it categorized the type of equipment the powerlifter used. The three categories of equipment type are raw, single-ply, and wraps. The last variable is sex. The sex variable is a binary variable with only a male or female option. This dataset was chosen as I participate in powerlifting personally and am interested in the differences in powerlifting statistics based on equipment types as well as differences between the two sexes.</p>
<ul>
<li><strong>1. (15 pts)</strong> Perform a MANOVA testing whether any of your numeric variables (or a subset of them, if including them all doesn’t make sense) show a mean difference across levels of one of your categorical variables (3). If they do, perform univariate ANOVAs to find response(s) showing a mean difference across groups (3), and perform post-hoc t tests to find which groups differ (3). Discuss the number of tests you have performed, calculate the probability of at least one type I error (if unadjusted), and adjust the significance level accordingly (bonferroni correction) before discussing significant differences (3). Briefly discuss assumptions and whether or not they are likely to have been met (2).</li>
</ul>
<pre class="r"><code>mano&lt;-manova(cbind(best3squat,best3bench, best3deadlift)~equipment, data=liftdata)
summary(mano)</code></pre>
<pre><code>## Df Pillai approx F num Df den Df Pr(&gt;F)
## equipment 2 0.12718 534.85 6 47256 &lt; 2.2e-16 ***
## Residuals 23629
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1</code></pre>
<pre class="r"><code>summary.aov(mano)</code></pre>
<pre><code>## Response best3squat :
## Df Sum Sq Mean Sq F value Pr(&gt;F)
## equipment 2 7169805 3584903 682.48 &lt; 2.2e-16 ***
## Residuals 23629 124117267 5253
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1
##
## Response best3bench :
## Df Sum Sq Mean Sq F value Pr(&gt;F)
## equipment 2 2544755 1272377 413.85 &lt; 2.2e-16 ***
## Residuals 23629 72647615 3075
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1
##
## Response best3deadlift :
## Df Sum Sq Mean Sq F value Pr(&gt;F)
## equipment 2 1280991 640495 160.8 &lt; 2.2e-16 ***
## Residuals 23629 94116634 3983
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1</code></pre>
<pre class="r"><code>liftdata%&gt;%group_by(equipment)%&gt;%summarize(mean(best3squat),mean(best3bench), mean(best3deadlift))</code></pre>
<pre><code>## # A tibble: 3 x 4
## equipment `mean(best3squat)` `mean(best3bench)`
`mean(best3deadlift)`
## &lt;chr&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
## 1 Raw 183.  118.  207.
## 2 Single-ply 225.  142.  224.
## 3 Wraps 236.  156.  263.</code></pre>
<pre class="r"><code>pairwise.t.test(liftdata$best3squat,liftdata$equipment, p.adj=&quot;none&quot;)</code></pre>
<pre><code>## 
##  Pairwise comparisons using t tests with pooled SD 
## 
## data:  liftdata$best3squat and liftdata$equipment 
## 
##            Raw     Single-ply
## Single-ply &lt; 2e-16 -         
## Wraps      7.4e-09 0.22      
## 
## P value adjustment method: none</code></pre>
<pre class="r"><code>pairwise.t.test(liftdata$best3bench,liftdata$equipment,p.adj=&quot;none&quot;)</code></pre>
<pre><code>## 
##  Pairwise comparisons using t tests with pooled SD 
## 
## data:  liftdata$best3bench and liftdata$equipment 
## 
##            Raw     Single-ply
## Single-ply &lt; 2e-16 -         
## Wraps      5.2e-08 0.057     
## 
## P value adjustment method: none</code></pre>
<pre class="r"><code>pairwise.t.test(liftdata$best3deadlift,liftdata$equipment,p.adj=&quot;none&quot;)</code></pre>
<pre><code>## 
##  Pairwise comparisons using t tests with pooled SD 
## 
## data:  liftdata$best3deadlift and liftdata$equipment 
## 
##            Raw     Single-ply
## Single-ply &lt; 2e-16 -         
## Wraps      2.4e-12 8.9e-07   
## 
## P value adjustment method: none</code></pre>
<pre class="r"><code>#probability of type I error
1-(.95)^9</code></pre>
<pre><code>## [1] 0.3697506</code></pre>
<pre class="r"><code>#Bonferroni correction
0.05/13</code></pre>
<pre><code>## [1] 0.003846154</code></pre>
<p>The MANOVA test was chosen to be ran to determine whether the variables best3squat, best3bench, and best3deadlift differed by the type of equipment used. The null hypothesis for the test was determined to be: The variables best3squat, best3bench, and best3deadlift were equal for the three equipment types described. The alternative hypothesis was determined to be: For at least one of the variables (best3squat, best3bench, and best3deadlift), the equipment type mean was different at least once. The MANOVA test results were significant which showed that there were significant differences found between the types of equipment in the dataset on the variables best3squat, best3bench, and best3deadlift (Pillai trace = 0.127, pseudo F(6,47256)=534.85, p&lt;0.0001). In addition, a univariate ANOVA was performed to determine the responses that shows the mean differences across the groups (best3squat, best3bench, and best3deadlift). The univariate ANOVA for best3squat, best3bench, and best3deadlift were determined to be significant (F(2,23629)=682.48, p&lt;0.0001, F(2,23629)=413.85, p&lt;0.0001, and F(2, 23269)=160.8, p&lt;0.0001 based on the order of best3squat, best3bench, and best3deadlift). After the t-test was performed, it was determined that raw and wraps and raw and single-ply differed significantly for best3squat. Raw and wraps, raw and single-ply and single-ply and wraps were determined to differ significantly for best3deadlift. Raw and single-ply and raw and wraps differed significantly for best3bench. There was a total of 1 MANOVA, 3 ANOVA, and 9 t-tests performed in the order described for a grand total of 13 tests. The probability of type I error was calculated to be 0.37, and the adjusted significance level was calculated to be 0.0038 according to the Bonferroni correction. The post-hoc tests were not affected by the new significance and the significance of the differences remained the same. The assumptions for the MANOVA test performed includes random samples, independent observation, multivariate normality of the dependent variables, homogeneity of the within group covariance matrices, a linear relationship between the dependent variables, no extreme multivariate or univariate outliers, and no multicollinearity. Unfortunately, not all of the assumptions were met in my test. The assumption on no multicollinearity was not met as my three dependent variables were likely to be correlated. There was also not a linear relationship among the dependent variables. All the other assumptions were met.</p>
<ul>
<li><strong>2. (10 pts)</strong> Perform some kind of randomization test on your data (that makes sense). This can be anything you want! State null and alternative hypotheses, perform the test, and interpret the results (7). Create a plot visualizing the null distribution and the test statistic (3).</li>
</ul>
<pre class="r"><code>t.test(data=liftdata, bodyweight~sex)</code></pre>
<pre><code>##
## Welch Two Sample t-test
##
## data: bodyweight by sex
## t = -84.475, df = 21803, p-value &lt; 2.2e-16
## alternative hypothesis: true difference in means is not
equal to 0
## 95 percent confidence interval:
## -23.42733 -22.36482
## sample estimates:
## mean in group F mean in group M
## 64.97561 87.87168</code></pre>
<pre class="r"><code>bodweight&lt;-liftdata%&gt;%dplyr::select(1,6)
bodweight%&gt;%dplyr::group_by(sex)%&gt;%dplyr::summarize(means=mean(bodyweight))%&gt;%dplyr::summarize(`mean_diff:`=diff(means))</code></pre>
<pre><code>## # A tibble: 1 x 1
##   `mean_diff:`
##          &lt;dbl&gt;
## 1         22.9</code></pre>
<pre class="r"><code>randomdist&lt;-vector()
for(i in 1:5000){
proj2dat&lt;-data.frame(bodyweight=sample(liftdata$bodyweight),sex=liftdata$sex)
randomdist[i]&lt;-mean(proj2dat[proj2dat$sex==&quot;M&quot;,]$bodyweight)-
mean(proj2dat[proj2dat$sex==&quot;F&quot;,]$bodyweight)}
{hist(randomdist,main=&quot;&quot;,ylab=&quot;&quot;); abline(v =22.8,col=&quot;red&quot;)}</code></pre>
<p><img src="../Project2_files/figure-html/unnamed-chunk-3-1.png" width="768" style="display: block; margin: auto;" /> I performed a t-test on sex and bodyweight. My null hypothesis was that there was no difference in the means of the bodyweight variable between the two sexes. My alternative hypothesis was that there was a significant difference in the means of the bodyweight variable between the two sexes. The t-test results indicated that there was a significant difference in bodyweight between the two sexes (p-value &lt; 0.05). The males had an average body weight of 87.872kg, while the females had an average body weight of 64.976 kg.</p>
<ul>
<li><p><strong>3. (35 pts)</strong> Build a linear regression model predicting one of your response variables from at least 2 other variables, including their interaction. Mean-center any numeric variables involved in the interaction.</p>
<ul>
<li>Interpret the coefficient estimates (do not discuss significance) (10)</li>
<li>Plot the regression using <code>ggplot()</code>. If your interaction is numeric by numeric, refer to code near the end of WS15 to make the plot. If you have 3 or more predictors, just chose two to plot for convenience. (8)</li>
<li>Check assumptions of linearity, normality, and homoskedasticity either graphically or using a hypothesis test (4)</li>
<li>Regardless, recompute regression results with robust standard errors via <code>coeftest(..., vcov=vcovHC(...))</code>. Discuss significance of results, including any changes from before/after robust SEs if applicable. (8)</li>
<li>What proportion of the variation in the outcome does your model explain? (4)</li>
</ul></li>
</ul>
<pre class="r"><code>library(lmtest)
library(sandwich)
liftdata$best3squat_c &lt;- liftdata$best3squat - mean(liftdata$best3squat)
liftdata$best3bench_c&lt;-liftdata$best3bench - mean(liftdata$best3bench)
liftdata$bodyweight_c&lt;-liftdata$bodyweight-mean(liftdata$bodyweight)
liftfit&lt;-lm(bodyweight~best3squat_c*best3bench_c, data=liftdata)
summary(liftfit)</code></pre>
<pre><code>##
## Call:
## lm(formula = bodyweight ~ best3squat_c * best3bench_c,
data = liftdata)
##
## Residuals:
## Min 1Q Median 3Q Max
## -46.982 -11.273 -2.817 8.611 117.195
##
## Coefficients:
## Estimate Std. Error t value Pr(&gt;|t|)
## (Intercept) 7.903e+01 1.386e-01 570.369 &lt;2e-16 ***
## best3squat_c 1.159e-01 3.719e-03 31.154 &lt;2e-16 ***
## best3bench_c 1.612e-01 5.001e-03 32.239 &lt;2e-16 ***
## best3squat_c:best3bench_c 1.921e-04 2.211e-05 8.689
&lt;2e-16 ***
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1
##
## Residual standard error: 16.77 on 23628 degrees of
freedom
## Multiple R-squared: 0.5276, Adjusted R-squared: 0.5275
## F-statistic: 8795 on 3 and 23628 DF, p-value: &lt; 2.2e-16</code></pre>
<pre class="r"><code>newlift&lt;-liftdata
newlift$best3squat_c&lt;-mean(liftdata$best3squat_c)
newlift$mean&lt;-predict(liftfit,newlift)
newlift$best3squat_c&lt;-mean(liftdata$best3squat_c)+sd(liftdata$best3squat_c)
newlift$plus.sd&lt;-predict(liftfit,newlift)
newlift$best3squat_c&lt;-mean(liftdata$best3squat_c)-sd(liftdata$best3squat_c)
newlift$minus.sd&lt;-predict(liftfit,newlift)
intnew&lt;-newlift%&gt;%select(bodyweight,best3bench_c,mean,plus.sd,minus.sd)%&gt;%gather(best3squat,value,-bodyweight,-best3bench_c)
liftcols&lt;-c(&quot;#619CFF&quot;,&quot;#F8766D&quot;,&quot;#00BA38&quot;)
names(liftcols)&lt;-c(&quot;-1 sd&quot;,&quot;mean&quot;,&quot;+1 sd&quot;)
liftcols=as.factor(liftcols)
ggplot(liftdata,aes(best3bench_c,bodyweight),group=liftcols)+geom_point()+geom_line(data=newlift,aes(y=mean,color=&quot;mean&quot;))+geom_line(data=newlift,aes(y=plus.sd,color=&quot;+1sd&quot;))+geom_line(data=newlift,aes(y=minus.sd,color=&quot;-1sd&quot;))+scale_color_manual(values=liftcols)+labs(color=&quot;Best 3 squats&quot;)+theme(legend.position=c(.9,.2))</code></pre>
<p><img src="../Project2_files/figure-html/unnamed-chunk-4-1.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code>qplot(x=best3bench_c,y=bodyweight,color=best3squat_c,data=liftdata)+stat_smooth(method=&quot;lm&quot;,se=FALSE,fullrange=TRUE)</code></pre>
<p><img src="../Project2_files/figure-html/unnamed-chunk-4-2.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code>liftresid&lt;-liftfit$residuals
liftfitval&lt;-liftfit$fitted.values
ggplot()+geom_point(aes(liftfitval,liftresid))+geom_hline(yintercept=0, color=&#39;red&#39;)</code></pre>
<p><img src="../Project2_files/figure-html/unnamed-chunk-4-3.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code>ggplot()+geom_histogram(aes(liftresid), bins=20)</code></pre>
<p><img src="../Project2_files/figure-html/unnamed-chunk-4-4.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code>ggplot()+geom_qq(aes(sample=liftresid))+geom_qq_line(aes(sample=liftresid))</code></pre>
<p><img src="../Project2_files/figure-html/unnamed-chunk-4-5.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code>bptest(liftfit)</code></pre>
<pre><code>## 
##  studentized Breusch-Pagan test
## 
## data:  liftfit
## BP = 595.01, df = 3, p-value &lt; 2.2e-16</code></pre>
<pre class="r"><code>coeftest(liftfit, vcov = vcovHC(liftfit))</code></pre>
<pre><code>##
## t test of coefficients:
##
## Estimate Std. Error t value Pr(&gt;|t|)
## (Intercept) 7.9033e+01 1.4469e-01 546.2405 &lt; 2.2e-16 ***
## best3squat_c 1.1588e-01 4.6289e-03 25.0330 &lt; 2.2e-16 ***
## best3bench_c 1.6121e-01 6.1768e-03 26.0995 &lt; 2.2e-16 ***
## best3squat_c:best3bench_c 1.9214e-04 2.3079e-05 8.3253 &lt;
2.2e-16 ***
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1</code></pre>
<pre class="r"><code>liftfit1&lt;-lm(bodyweight~best3squat_c+best3bench_c, data=liftdata)
summary(liftfit1)</code></pre>
<pre><code>##
## Call:
## lm(formula = bodyweight ~ best3squat_c + best3bench_c,
data = liftdata)
##
## Residuals:
## Min 1Q Median 3Q Max
## -47.201 -11.266 -2.689 8.574 115.662
##
## Coefficients:
## Estimate Std. Error t value Pr(&gt;|t|)
## (Intercept) 79.775898 0.109256 730.18 &lt;2e-16 ***
## best3squat_c 0.113956 0.003719 30.64 &lt;2e-16 ***
## best3bench_c 0.169614 0.004914 34.52 &lt;2e-16 ***
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1
##
## Residual standard error: 16.8 on 23629 degrees of
freedom
## Multiple R-squared: 0.526, Adjusted R-squared: 0.526
## F-statistic: 1.311e+04 on 2 and 23629 DF, p-value: &lt;
2.2e-16</code></pre>
<pre class="r"><code>anova(liftfit,liftfit1,test=&quot;LRT&quot;)</code></pre>
<pre><code>## Analysis of Variance Table
##
## Model 1: bodyweight ~ best3squat_c * best3bench_c
## Model 2: bodyweight ~ best3squat_c + best3bench_c
## Res.Df RSS Df Sum of Sq Pr(&gt;Chi)
## 1 23628 6644286
## 2 23629 6665515 -1 -21229 &lt; 2.2e-16 ***
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1</code></pre>
<p>A linear regression was performed to predict the bodyweight in kg from the best3squat and best3bench variables. The null hypothesis was that there was no interaction between the best3squat and best3bench variables on the bodyweight variable. The alternative hypothesis was that there is an interaction between the best3squat and best3bench variables on the bodyweight variable. The intercepts was interpreted as for every 1kg increase in the best3bench variable, the bodyweight variable increased by 1.612e-01 kg. In addition, the interaction showed that for every 1kg increase in the best3squat variable, the bodyweight variable increases by an average of 1.159e-01 kg. Finally, the interaction also showed the for every 1kg increase in both the variables best3bench and best3squat, the bodyweight variable increases by 1.921e-04 kg. The assumptions for linearity, normality and homoskedasticity were checked graphically. Homoskedasticity and linearity were confirmed to be met by plotting the liftfitval by the fitresid in ggplot. The assumption of normality was confirmed by making a line graph of theoretical vs. sample and by making a histogram of the residuals. Following confirming the assumptions, the regression was recomputed using the results with robust standard errors. The results obtained from robust standard errors differed from the results obtained before as the new SE values were all larger than before. The change in SE did not change the significance of any of the predictors in the model. The model computed explained 52.6% of the variation in the outcomes. This was calculated from the adjusted R-squared value.</p>
<ul>
<li><strong>4. (5 pts)</strong> Rerun same regression model (with interaction), but this time compute bootstrapped standard errors. Discuss any changes you observe in SEs and p-values using these SEs compared to the original SEs and the robust SEs)</li>
</ul>
<pre class="r"><code>sample_distn&lt;-replicate(1000,{
boot_dat&lt;-liftdata[sample(nrow(liftdata), replace=TRUE),]
liftfit2&lt;-lm(bodyweight~best3squat_c*best3bench_c, data=boot_dat)
coef(liftfit2)})
sample_distn%&gt;%t%&gt;%as.data.frame%&gt;%summarize_all(sd)</code></pre>
<pre><code>## (Intercept) best3squat_c best3bench_c
best3squat_c:best3bench_c
## 1 0.1454616 0.004776482 0.006323161 2.302825e-05</code></pre>
<p>The same regression was re-ran with the bootstrapped SE. The SE obtained were slightly different than the robust SE and the original. The newly obtained bootstrapped SE for the intercept was determined to be 0.1464866, while the original was determined to be 0.139. The best3squat SE for the bootstrap was determined to be 0.004691988 while the original was 0.0037. the best3bench bootstrapped SE was determined to be 0.006265698 while the original was 0.005. The bootstrapped SE for the interaction was determined to be 2.353e-05 while the original was determined to be 2.21e-05. Overall, the bootstrapped SE were all a little bit higher than the originals. In comparison to the robust SE, the bootstrapped SE were all very close together. The p-values were still below 0.05 in the bootstrapped SE.</p>
<ul>
<li><p><strong>5. (40 pts)</strong> Perform a logistic regression predicting a binary categorical variable (if you don’t have one, make/get one) from at least two explanatory variables (interaction not necessary).</p>
<ul>
<li>Interpret coefficient estimates in context (10)</li>
<li>Report a confusion matrix for your logistic regression (2)</li>
<li>Compute and discuss the Accuracy, Sensitivity (TPR), Specificity (TNR), and Recall (PPV) of your model (5)</li>
<li>Using ggplot, plot density of log-odds (logit) by your binary outcome variable (3)</li>
<li>Generate an ROC curve (plot) and calculate AUC (either manually or with a package); interpret (10)</li>
<li>Perform 10-fold (or repeated random sub-sampling) CV and report average out-of-sample Accuracy, Sensitivity, and Recall (10)</li>
</ul></li>
</ul>
<pre class="r"><code>liftdata1&lt;-liftdata%&gt;%mutate(y=ifelse(sex==&quot;M&quot;, 1,0))
liftfit3&lt;-glm(y~bodyweight+best3squat, data=liftdata1, family=binomial)
summary(liftfit3)</code></pre>
<pre><code>##
## Call:
## glm(formula = y ~ bodyweight + best3squat, family =
binomial,
## data = liftdata1)
##
## Deviance Residuals:
## Min 1Q Median 3Q Max
## -3.1970 -0.5605 0.1738 0.5566 2.9244
##
## Coefficients:
## Estimate Std. Error z value Pr(&gt;|z|)
## (Intercept) -6.2115613 0.0933443 -66.545 &lt; 2e-16 ***
## bodyweight 0.0042871 0.0011709 3.661 0.000251 ***
## best3squat 0.0333832 0.0005073 65.806 &lt; 2e-16 ***
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1
##
## (Dispersion parameter for binomial family taken to be 1)
##
## Null deviance: 30705 on 23631 degrees of freedom
## Residual deviance: 17693 on 23629 degrees of freedom
## AIC: 17699
##
## Number of Fisher Scoring iterations: 6</code></pre>
<pre class="r"><code>exp(coef(liftfit3))</code></pre>
<pre><code>## (Intercept)  bodyweight  best3squat 
## 0.002006103 1.004296353 1.033946651</code></pre>
<pre class="r"><code>prob&lt;-predict(liftfit3, type=&quot;response&quot;)
table(predict=as.numeric(prob&gt;.5), truth=liftdata1$y)%&gt;%addmargins</code></pre>
<pre><code>##        truth
## predict     0     1   Sum
##     0    6290  1814  8104
##     1    2066 13462 15528
##     Sum  8356 15276 23632</code></pre>
<pre class="r"><code>#accuracy
(6290+13462)/23632</code></pre>
<pre><code>## [1] 0.8358158</code></pre>
<pre class="r"><code>#tnr (specificity)
(6290)/8104</code></pre>
<pre><code>## [1] 0.7761599</code></pre>
<pre class="r"><code>#tpr (sensitivity aka recall)
(13462)/15528</code></pre>
<pre><code>## [1] 0.86695</code></pre>
<pre class="r"><code>#ppv (precision)
(13462)/(15276)</code></pre>
<pre><code>## [1] 0.8812516</code></pre>
<pre class="r"><code>liftdata1$y &lt;-as.factor(liftdata1$y)
liftdata1$logit&lt;-predict(liftfit3, type=&quot;link&quot;)
liftdata1%&gt;%ggplot()+geom_density(aes(logit, color=y, fill=y), alpha=.4)+geom_vline(xintercept = 0)+xlab(&quot;predictor (logit)&quot;)</code></pre>
<p><img src="../Project2_files/figure-html/unnamed-chunk-6-1.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code>library(plotROC)
prob1&lt;-predict(liftfit3, type=&quot;response&quot;)
ROCplot&lt;-ggplot(liftdata1)+geom_roc(aes(d=sex,m=prob1), n.cuts=0)+geom_segment(aes(x=0, xend=1, y=0, yend=1), lty=2)
ROCplot</code></pre>
<p><img src="../Project2_files/figure-html/unnamed-chunk-6-2.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code>calc_auc(ROCplot)</code></pre>
<pre><code>##   PANEL group       AUC
## 1     1    -1 0.9033721</code></pre>
<pre class="r"><code>class_diag&lt;-function(probs,truth){
tab&lt;-table(factor(probs&gt;.5,levels=c(&quot;FALSE&quot;,&quot;TRUE&quot;)),truth)
acc=sum(diag(tab))/sum(tab)
sens=tab[2,2]/colSums(tab)[2]
spec=tab[1,1]/colSums(tab)[1]
ppv=tab[2,2]/rowSums(tab)[2]
if(is.numeric(truth)==FALSE &amp; is.logical(truth)==FALSE) truth&lt;-as.numeric(truth)-1
#CALCULATE EXACT AUC
ord&lt;-order(probs, decreasing=TRUE)
probs &lt;- probs[ord]; truth &lt;- truth[ord]
TPR=cumsum(truth)/max(1,sum(truth))
FPR=cumsum(!truth)/max(1,sum(!truth))
dup&lt;-c(probs[-1]&gt;=probs[-length(probs)], FALSE)
TPR&lt;-c(0,TPR[!dup],1); FPR&lt;-c(0,FPR[!dup],1)
n &lt;- length(TPR)
auc&lt;- sum( ((TPR[-1]+TPR[-n])/2) * (FPR[-1]-FPR[-n]) )
data.frame(acc,sens,spec,ppv,auc)
}
set.seed(1234)
k=10
liftdata2&lt;-liftdata1[sample(nrow(liftdata1)),]
folds&lt;-cut(seq(1:nrow(liftdata1)),breaks=k,labels=F)
diags&lt;-NULL
for(i in 1:k){
train&lt;-liftdata2[folds!=i,]
test&lt;-liftdata2[folds==i,]
truth&lt;-test$y
fit&lt;-glm(y~bodyweight+best3squat,data=train,family=&quot;binomial&quot;)
probs&lt;-predict(fit,newdata = test,type=&quot;response&quot;)
diags&lt;-rbind(diags,class_diag(probs,truth))
}
apply(diags,2, mean)</code></pre>
<pre><code>##       acc      sens      spec       ppv       auc 
## 0.8356038 0.8811521 0.7525472 0.8667696 0.9032786</code></pre>
<p>A logistic regression was performed to predict sex from bodyweight and best3squat. The sex variable was binary, coded as males=1 and females=0. There was a significant effect of best3squat and bodyweight on the prediction of whether or not the powerlifter was male (p&lt;0.05). The coefficients were interpreted using a log function. For every 1kg increase in the bodyweight variable, the odds of being male was multiplied by a factor of 1.004296. For every 1kg increase in the best3squat variable, the odds of the powerlifter being male was multiplied by a factor of 1.033947. With the confusion matrix, the accuracy was determined to be 0.8358158, the specificity was determined to be 0.7761599, the sensitivity was determined to be 0.86695, and the PPV was determined to be 0.8812516. The accuracy was the proportion of the correctly sexually classified powerlifters, the accuracy obtained was very good. The specificity was the proportion of women that were correctly sexually classified, and the specificity obtained were also really good. The sensitivity was the true positive rate which was the proportion of men that were correctly sexually classified, and it also had a good result. Ggplot was then used to plot the density of log-odds by the primary outcome variable (sex). The ROC curve was also generated and the AUC (area under the curve) was calculated to be 0.903. The AUC obtained was really good for the prediction of the outcome. Finally, a 10-fold cross variation was performed and the accuracy was determined to be 0.8356038, the sensitivity was determined to be 0.8811521, the specificity was determined to be 0.7525472, PPV to be 0.8667696, and AUC to be 0.9032786.</p>
<ul>
<li><strong>6. (10 pts)</strong> Choose one variable you want to predict (can be one you used from before; either binary or continuous) and run a LASSO regression inputting all the rest of your variables as predictors. Choose lambda to give the simplest model whose accuracy is near that of the best (i.e., <code>lambda.1se</code>). Discuss which variables are retained. Perform 10-fold CV using this model: if response in binary, compare model’s out-of-sample accuracy to that of your logistic regression in part 5; if response is numeric, compare the residual standard error (at the bottom of the summary output, aka RMSE): lower is better fit!</li>
</ul>
<pre class="r"><code>library(glmnet)
library(dplyr)
select&lt;-dplyr::select
lassodata&lt;-liftdata3%&gt;%mutate(y=ifelse(sex==&quot;M&quot;, 1,0))
lassodata&lt;-lassodata%&gt;%select(-sex)
fit_lasso&lt;-lm(y~.,data=lassodata)
yhat&lt;-predict(fit_lasso)
mean((lassodata$y-yhat)^2)</code></pre>
<pre><code>## [1] 0.1065739</code></pre>
<pre class="r"><code>y&lt;-as.matrix(lassodata$y)
x &lt;- model.matrix(y~ ., data =lassodata)
cv&lt;-cv.glmnet(x,y, family=&#39;binomial&#39;)
lasso&lt;-glmnet(x,y,family=&quot;binomial&quot;,lambda=cv$lambda.1se)
coef(lasso)</code></pre>
<pre><code>## 8 x 1 sparse Matrix of class &quot;dgCMatrix&quot;
##                              s0
## (Intercept)         -8.47061922
## (Intercept)          .         
## bodyweight          -0.01224872
## maxsquat            -0.01058432
## maxbench             0.02809051
## maxdead              0.04454348
## equipmentSingle-ply -0.30988264
## equipmentWraps       0.48083577</code></pre>
<pre class="r"><code>lass&lt;-rownames(coef(lasso))[which(coef(lasso)!=0)]
select&lt;-dplyr::select
lassodata1&lt;-x%&gt;% as.data.frame%&gt;%select(lass)%&gt;%mutate(y=lassodata$y)
set.seed(1234)
k=10
data9999&lt;-lassodata1[sample(nrow(lassodata)),]
folds9999&lt;-cut(seq(1:nrow(lassodata)), breaks=k, labels=FALSE)
diags9999&lt;-NULL
for(i in 1:k){
  train9999&lt;-data9999[folds9999!=i,]
test9999&lt;-data9999[folds9999==i,]
truth9999&lt;-test9999$y
fit9999&lt;-glm(y~., data=train9999, family=&quot;binomial&quot;)
probs9999&lt;-predict(fit9999, newdata=test9999, type=&quot;response&quot;)
preds9999&lt;-ifelse(probs9999&gt;0.5, 1, 0)
diags9999&lt;-rbind(diags9999, class_diag(probs9999, truth9999))
}
apply(diags9999,2, mean)</code></pre>
<pre><code>##       acc      sens      spec       ppv       auc 
## 0.8870457 0.9116816 0.8419287 0.9137124 0.9526139</code></pre>
<p>A LASSO regression was used to predict sex from the other variables in the dataset. All of the variables were retained as they all had non-zero coefficients which was surprising. In reality it does biologically makes sense as males typically can lift more weights than females due to higher muscle and bone density. The accuracy was determined to be 0.8870457, sensitivity to be 0.9116816, specificity to be 0.8419287, PPV to be 0.9137124, and AUC to be 0.9526139 (amazing area under the curve). Compared to the results obtained from the logistic regression from question 5, the results obtained from the lasso regression were all higher. This was consistent with the logic that only the best predictors were used to predict sex in the lasso regression.</p>
</div>
<div id="where-do-i-find-data-again" class="section level2">
<h2>Where do I find data again?</h2>
<p>You can choose ANY datasets you want that meet the above criteria for variables and observations. You can make it as serious as you want, or not, but keep in mind that you will be incorporating this project into a portfolio webpage for your final in this course, so choose something that really reflects who you are, or something that you feel will advance you in the direction you hope to move career-wise, or something that you think is really neat, or whatever. On the flip side, regardless of what you pick, you will be performing all the same tasks, so it doesn’t end up being that big of a deal.</p>
<p>If you are totally clueless and have no direction at all, log into the server and type</p>
<pre class="r"><code>data(package = .packages(all.available = TRUE))</code></pre>
<p>This will print out a list of <strong>ALL datasets in ALL packages</strong> installed on the server (a ton)! Scroll until your eyes bleed! Actually, do not scroll that much… To start with something more manageable, just run the command on your own computer, or just run <code>data()</code> to bring up the datasets in your current environment. To read more about a dataset, do <code>?packagename::datasetname</code>.</p>
<p>If it is easier for you, and in case you don’t have many packages installed, a list of R datasets from a few common packages (also downloadable in CSV format) is given at the following website: <a href="https://vincentarelbundock.github.io/Rdatasets/datasets.html" class="uri">https://vincentarelbundock.github.io/Rdatasets/datasets.html</a>.</p>
<ul>
<li><p>A good package to download for fun/relevant data is <code>fivethiryeight</code>. Run <code>install.packages(&quot;fivethirtyeight&quot;),</code> load the packages with <code>library(fivethirtyeight)</code>, run <code>data()</code>, and then scroll down to view the datasets. Here is an online list of all 127 datasets (with links to the 538 articles). Lots of sports, politics, current events, etc.</p></li>
<li><p>If you have already started to specialize (e.g., ecology, epidemiology) you might look at discipline-specific R packages (vegan, epi, respectively). We will be using some tools from these packages later in the course, but they come with lots of data too, which you can explore according to the directions above</p></li>
<li><p>However, you <em>emphatically DO NOT</em> have to use datasets available via R packages! In fact, I would much prefer it if you found the data from completely separate sources and brought them together (a much more realistic experience in the real world)! You can even reuse data from your SDS328M project, provided it shares a variable in common with other data which allows you to merge the two together (e.g., if you still had the timestamp, you could look up the weather that day: <a href="https://www.wunderground.com/history/" class="uri">https://www.wunderground.com/history/</a>). If you work in a research lab or have access to old data, you could potentially merge it with new data from your lab!</p></li>
<li><p>Here is a curated list of interesting datasets (read-only spreadsheet format): <a href="https://docs.google.com/spreadsheets/d/1wZhPLMCHKJvwOkP4juclhjFgqIY8fQFMemwKL2c64vk/edit" class="uri">https://docs.google.com/spreadsheets/d/1wZhPLMCHKJvwOkP4juclhjFgqIY8fQFMemwKL2c64vk/edit</a></p></li>
<li><p>Here is another great compilation of datasets: <a href="https://github.com/rfordatascience/tidytuesday" class="uri">https://github.com/rfordatascience/tidytuesday</a></p></li>
<li><p>Here is the UCI Machine Learning Repository: <a href="https://archive.ics.uci.edu/ml/index.php" class="uri">https://archive.ics.uci.edu/ml/index.php</a></p>
<ul>
<li>See also <a href="https://en.wikipedia.org/wiki/List_of_datasets_for_machine-learning_research#Biological_data" class="uri">https://en.wikipedia.org/wiki/List_of_datasets_for_machine-learning_research#Biological_data</a></li>
</ul></li>
<li><p>Here is another good general place to look: <a href="https://www.kaggle.com/datasets" class="uri">https://www.kaggle.com/datasets</a></p></li>
<li><p>To help narrow your search down or to see interesting variable ideas, check out <a href="https://www.tylervigen.com/spurious-correlations" class="uri">https://www.tylervigen.com/spurious-correlations</a>. This is the spurious correlations website, and it is fun, but if you look at the bottom of each plot you will see sources for the data. This is a good place to find very general data (or at least get a sense of where you can scrape data together from)!</p></li>
<li><p>If you are interested in medical data, check out www.countyhealthrankings.org</p></li>
<li><p>If you are interested in scraping UT data, they make <em>loads</em> of data public (e.g., beyond just professor CVs and syllabi). Check out all the data that is available in the statistical handbooks: <a href="https://reports.utexas.edu/statistical-handbook" class="uri">https://reports.utexas.edu/statistical-handbook</a></p></li>
</ul>
<div id="broader-data-sources" class="section level5">
<h5>Broader data sources:</h5>
<p><a href="www.data.gov">Data.gov</a> 186,000+ datasets!</p>
<p><a href="Social%20Explorer">Social Explorer</a> is a nice interface to Census and American Community Survey data (more user-friendly than the government sites). May need to sign up for a free trial.</p>
<p><a href="www.bls.gov">U.S. Bureau of Labor Statistics</a></p>
<p><a href="www.census.gov">U.S. Census Bureau</a></p>
<p><a href="www.gapminder.org/data">Gapminder</a>, data about the world.</p>
<p>…</p>
</div>
</div>
</div>

              <hr>
              <div class="related-posts">
                <h5>Related Posts</h5>
                
              </div>
            </div>
          </div>
          <hr>
        <div class="disqus">
  <div id="disqus_thread"></div>
  <script type="text/javascript">

    (function() {
      
      
      if (window.location.hostname == "localhost")
        return;

      var disqus_shortname = '';
      var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
      dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
      (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
    })();
  </script>
  <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
  <a href="http://disqus.com/" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>
</div>
        </div>
      </div>
      
    </div>

    
    <footer>
  <div id="footer">
    <div class="container">
      <p class="text-muted">&copy; All rights reserved. Powered by <a href="https://gohugo.io/">Hugo</a> and
      <a href="http://www.github.com/nurlansu/hugo-sustain/">sustain</a> with ♥</p>
    </div>
  </div>
</footer>
<div class="footer"></div>


<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="../js/docs.min.js"></script>
<script src="../js/main.js"></script>

<script src="../js/ie10-viewport-bug-workaround.js"></script>


    
  </body>
</html>
